# GitLab CI/CD Configuration
# Mirrors GitHub Actions workflows structure and functionality

# ==============================================================================
# GLOBAL CONFIGURATION
# ==============================================================================

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "api"

variables:
  PYTHON_VERSION: "3.12"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - validate
  - test
  - security
  - format
  - build
  - dependencies
  - version
  - release
  - status
  - sync

default:
  image: python:${PYTHON_VERSION}
  before_script:
    - python --version
    - python -m pip install --upgrade pip
  cache:
    key:
      files:
        - src/requirements.txt
    paths:
      - .cache/pip
    policy: pull-push

# ==============================================================================
# INCLUDE STAGE-SPECIFIC CONFIGURATIONS
# ==============================================================================

include:
  - local: '.gitlab-ci/validate.yml'
  - local: '.gitlab-ci/test.yml'
  - local: '.gitlab-ci/security.yml'
  - local: '.gitlab-ci/format.yml'
  - local: '.gitlab-ci/build.yml'
  - local: '.gitlab-ci/dependencies.yml'
  - local: '.gitlab-ci/version.yml'
  - local: '.gitlab-ci/release.yml'
  - local: '.gitlab-ci/status.yml'
  - local: '.gitlab-ci/sync.yml'