# ==============================================================================
# VERSION STAGE (mirrors version.yml)
# ==============================================================================

version-bump:
  stage: version
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - pip install bump2version build
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - git config --local user.name "gitlab-ci[bot]"
    - git config --local user.email "gitlab-ci[bot]@gitlab.com"
    - .gitlab-ci/scripts/determine-version-part.sh
    - .gitlab-ci/scripts/bump-version.sh
    - .gitlab-ci/scripts/sync-version-to-dev.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "api"