name: Security Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  PYTHON_VERSION: "3.12"

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install safety bandit

      - name: Run safety check (dependency vulnerabilities)
        run: |
          echo "Checking for known security vulnerabilities in dependencies..."
          safety check --json || echo "Safety check completed with warnings"

      - name: Run bandit security linter
        run: |
          echo "Running bandit security linter..."
          bandit -r src/ -f json || echo "Bandit scan completed with warnings"

      - name: Check for secrets in code
        run: |
          echo "Checking for potential secrets..."
          grep -r -i "password\|secret\|token\|key\|api" src/ || echo "No obvious secrets found"